package pl.srw.billcalculator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PGE_BILL.
 */
public class PgeBill {

    private Long id;
    private Integer readingFrom;
    private Integer readingTo;
    private Integer readingDayFrom;
    private Integer readingDayTo;
    private Integer readingNightFrom;
    private Integer readingNightTo;
    private java.util.Date dateFrom;
    private java.util.Date dateTo;
    private String cenaZaEnergieCzynna;
    private String cenaSkladnikJakosciowy;
    private String cenaOplataSieciowa;
    private String cenaOplataPrzejsciowa;
    private String cenaOplStalaZaPrzesyl;
    private String cenaOplataAbonamentowa;
    private String cenaZaEnergieCzynnaDzien;
    private String cenaZaEnergieCzynnaNoc;
    private String cenaOplataSieciowaDzien;
    private String cenaOplataSieciowaNoc;

    public PgeBill() {
    }

    public PgeBill(Long id) {
        this.id = id;
    }

    public PgeBill(Long id, Integer readingFrom, Integer readingTo, Integer readingDayFrom, Integer readingDayTo, Integer readingNightFrom, Integer readingNightTo, java.util.Date dateFrom, java.util.Date dateTo, String cenaZaEnergieCzynna, String cenaSkladnikJakosciowy, String cenaOplataSieciowa, String cenaOplataPrzejsciowa, String cenaOplStalaZaPrzesyl, String cenaOplataAbonamentowa, String cenaZaEnergieCzynnaDzien, String cenaZaEnergieCzynnaNoc, String cenaOplataSieciowaDzien, String cenaOplataSieciowaNoc) {
        this.id = id;
        this.readingFrom = readingFrom;
        this.readingTo = readingTo;
        this.readingDayFrom = readingDayFrom;
        this.readingDayTo = readingDayTo;
        this.readingNightFrom = readingNightFrom;
        this.readingNightTo = readingNightTo;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.cenaZaEnergieCzynna = cenaZaEnergieCzynna;
        this.cenaSkladnikJakosciowy = cenaSkladnikJakosciowy;
        this.cenaOplataSieciowa = cenaOplataSieciowa;
        this.cenaOplataPrzejsciowa = cenaOplataPrzejsciowa;
        this.cenaOplStalaZaPrzesyl = cenaOplStalaZaPrzesyl;
        this.cenaOplataAbonamentowa = cenaOplataAbonamentowa;
        this.cenaZaEnergieCzynnaDzien = cenaZaEnergieCzynnaDzien;
        this.cenaZaEnergieCzynnaNoc = cenaZaEnergieCzynnaNoc;
        this.cenaOplataSieciowaDzien = cenaOplataSieciowaDzien;
        this.cenaOplataSieciowaNoc = cenaOplataSieciowaNoc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getReadingFrom() {
        return readingFrom;
    }

    public void setReadingFrom(Integer readingFrom) {
        this.readingFrom = readingFrom;
    }

    public Integer getReadingTo() {
        return readingTo;
    }

    public void setReadingTo(Integer readingTo) {
        this.readingTo = readingTo;
    }

    public Integer getReadingDayFrom() {
        return readingDayFrom;
    }

    public void setReadingDayFrom(Integer readingDayFrom) {
        this.readingDayFrom = readingDayFrom;
    }

    public Integer getReadingDayTo() {
        return readingDayTo;
    }

    public void setReadingDayTo(Integer readingDayTo) {
        this.readingDayTo = readingDayTo;
    }

    public Integer getReadingNightFrom() {
        return readingNightFrom;
    }

    public void setReadingNightFrom(Integer readingNightFrom) {
        this.readingNightFrom = readingNightFrom;
    }

    public Integer getReadingNightTo() {
        return readingNightTo;
    }

    public void setReadingNightTo(Integer readingNightTo) {
        this.readingNightTo = readingNightTo;
    }

    public java.util.Date getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(java.util.Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    public java.util.Date getDateTo() {
        return dateTo;
    }

    public void setDateTo(java.util.Date dateTo) {
        this.dateTo = dateTo;
    }

    public String getCenaZaEnergieCzynna() {
        return cenaZaEnergieCzynna;
    }

    public void setCenaZaEnergieCzynna(String cenaZaEnergieCzynna) {
        this.cenaZaEnergieCzynna = cenaZaEnergieCzynna;
    }

    public String getCenaSkladnikJakosciowy() {
        return cenaSkladnikJakosciowy;
    }

    public void setCenaSkladnikJakosciowy(String cenaSkladnikJakosciowy) {
        this.cenaSkladnikJakosciowy = cenaSkladnikJakosciowy;
    }

    public String getCenaOplataSieciowa() {
        return cenaOplataSieciowa;
    }

    public void setCenaOplataSieciowa(String cenaOplataSieciowa) {
        this.cenaOplataSieciowa = cenaOplataSieciowa;
    }

    public String getCenaOplataPrzejsciowa() {
        return cenaOplataPrzejsciowa;
    }

    public void setCenaOplataPrzejsciowa(String cenaOplataPrzejsciowa) {
        this.cenaOplataPrzejsciowa = cenaOplataPrzejsciowa;
    }

    public String getCenaOplStalaZaPrzesyl() {
        return cenaOplStalaZaPrzesyl;
    }

    public void setCenaOplStalaZaPrzesyl(String cenaOplStalaZaPrzesyl) {
        this.cenaOplStalaZaPrzesyl = cenaOplStalaZaPrzesyl;
    }

    public String getCenaOplataAbonamentowa() {
        return cenaOplataAbonamentowa;
    }

    public void setCenaOplataAbonamentowa(String cenaOplataAbonamentowa) {
        this.cenaOplataAbonamentowa = cenaOplataAbonamentowa;
    }

    public String getCenaZaEnergieCzynnaDzien() {
        return cenaZaEnergieCzynnaDzien;
    }

    public void setCenaZaEnergieCzynnaDzien(String cenaZaEnergieCzynnaDzien) {
        this.cenaZaEnergieCzynnaDzien = cenaZaEnergieCzynnaDzien;
    }

    public String getCenaZaEnergieCzynnaNoc() {
        return cenaZaEnergieCzynnaNoc;
    }

    public void setCenaZaEnergieCzynnaNoc(String cenaZaEnergieCzynnaNoc) {
        this.cenaZaEnergieCzynnaNoc = cenaZaEnergieCzynnaNoc;
    }

    public String getCenaOplataSieciowaDzien() {
        return cenaOplataSieciowaDzien;
    }

    public void setCenaOplataSieciowaDzien(String cenaOplataSieciowaDzien) {
        this.cenaOplataSieciowaDzien = cenaOplataSieciowaDzien;
    }

    public String getCenaOplataSieciowaNoc() {
        return cenaOplataSieciowaNoc;
    }

    public void setCenaOplataSieciowaNoc(String cenaOplataSieciowaNoc) {
        this.cenaOplataSieciowaNoc = cenaOplataSieciowaNoc;
    }

}
