package pl.srw.billcalculator.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pl.srw.billcalculator.db.PgePrices;
import pl.srw.billcalculator.db.PgeG11Bill;
import pl.srw.billcalculator.db.PgeG12Bill;
import pl.srw.billcalculator.db.PgnigPrices;
import pl.srw.billcalculator.db.PgnigBill;
import pl.srw.billcalculator.db.TauronPrices;
import pl.srw.billcalculator.db.TauronG11Bill;
import pl.srw.billcalculator.db.History;

import pl.srw.billcalculator.db.dao.PgePricesDao;
import pl.srw.billcalculator.db.dao.PgeG11BillDao;
import pl.srw.billcalculator.db.dao.PgeG12BillDao;
import pl.srw.billcalculator.db.dao.PgnigPricesDao;
import pl.srw.billcalculator.db.dao.PgnigBillDao;
import pl.srw.billcalculator.db.dao.TauronPricesDao;
import pl.srw.billcalculator.db.dao.TauronG11BillDao;
import pl.srw.billcalculator.db.dao.HistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
@SuppressWarnings("ALL")
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pgePricesDaoConfig;
    private final DaoConfig pgeG11BillDaoConfig;
    private final DaoConfig pgeG12BillDaoConfig;
    private final DaoConfig pgnigPricesDaoConfig;
    private final DaoConfig pgnigBillDaoConfig;
    private final DaoConfig tauronPricesDaoConfig;
    private final DaoConfig tauronG11BillDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final PgePricesDao pgePricesDao;
    private final PgeG11BillDao pgeG11BillDao;
    private final PgeG12BillDao pgeG12BillDao;
    private final PgnigPricesDao pgnigPricesDao;
    private final PgnigBillDao pgnigBillDao;
    private final TauronPricesDao tauronPricesDao;
    private final TauronG11BillDao tauronG11BillDao;
    private final HistoryDao historyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pgePricesDaoConfig = daoConfigMap.get(PgePricesDao.class).clone();
        pgePricesDaoConfig.initIdentityScope(type);

        pgeG11BillDaoConfig = daoConfigMap.get(PgeG11BillDao.class).clone();
        pgeG11BillDaoConfig.initIdentityScope(type);

        pgeG12BillDaoConfig = daoConfigMap.get(PgeG12BillDao.class).clone();
        pgeG12BillDaoConfig.initIdentityScope(type);

        pgnigPricesDaoConfig = daoConfigMap.get(PgnigPricesDao.class).clone();
        pgnigPricesDaoConfig.initIdentityScope(type);

        pgnigBillDaoConfig = daoConfigMap.get(PgnigBillDao.class).clone();
        pgnigBillDaoConfig.initIdentityScope(type);

        tauronPricesDaoConfig = daoConfigMap.get(TauronPricesDao.class).clone();
        tauronPricesDaoConfig.initIdentityScope(type);

        tauronG11BillDaoConfig = daoConfigMap.get(TauronG11BillDao.class).clone();
        tauronG11BillDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        pgePricesDao = new PgePricesDao(pgePricesDaoConfig, this);
        pgeG11BillDao = new PgeG11BillDao(pgeG11BillDaoConfig, this);
        pgeG12BillDao = new PgeG12BillDao(pgeG12BillDaoConfig, this);
        pgnigPricesDao = new PgnigPricesDao(pgnigPricesDaoConfig, this);
        pgnigBillDao = new PgnigBillDao(pgnigBillDaoConfig, this);
        tauronPricesDao = new TauronPricesDao(tauronPricesDaoConfig, this);
        tauronG11BillDao = new TauronG11BillDao(tauronG11BillDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(PgePrices.class, pgePricesDao);
        registerDao(PgeG11Bill.class, pgeG11BillDao);
        registerDao(PgeG12Bill.class, pgeG12BillDao);
        registerDao(PgnigPrices.class, pgnigPricesDao);
        registerDao(PgnigBill.class, pgnigBillDao);
        registerDao(TauronPrices.class, tauronPricesDao);
        registerDao(TauronG11Bill.class, tauronG11BillDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        pgePricesDaoConfig.getIdentityScope().clear();
        pgeG11BillDaoConfig.getIdentityScope().clear();
        pgeG12BillDaoConfig.getIdentityScope().clear();
        pgnigPricesDaoConfig.getIdentityScope().clear();
        pgnigBillDaoConfig.getIdentityScope().clear();
        tauronPricesDaoConfig.getIdentityScope().clear();
        tauronG11BillDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
    }

    public PgePricesDao getPgePricesDao() {
        return pgePricesDao;
    }

    public PgeG11BillDao getPgeG11BillDao() {
        return pgeG11BillDao;
    }

    public PgeG12BillDao getPgeG12BillDao() {
        return pgeG12BillDao;
    }

    public PgnigPricesDao getPgnigPricesDao() {
        return pgnigPricesDao;
    }

    public PgnigBillDao getPgnigBillDao() {
        return pgnigBillDao;
    }

    public TauronPricesDao getTauronPricesDao() {
        return tauronPricesDao;
    }

    public TauronG11BillDao getTauronG11BillDao() {
        return tauronG11BillDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
