package pl.srw.billcalculator.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import pl.srw.billcalculator.db.PgePrices;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PGE_PRICES.
*/
public class PgePricesDao extends AbstractDao<PgePrices, Long> {

    public static final String TABLENAME = "PGE_PRICES";

    /**
     * Properties of entity PgePrices.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CenaZaEnergieCzynna = new Property(1, String.class, "cenaZaEnergieCzynna", false, "CENA_ZA_ENERGIE_CZYNNA");
        public final static Property CenaSkladnikJakosciowy = new Property(2, String.class, "cenaSkladnikJakosciowy", false, "CENA_SKLADNIK_JAKOSCIOWY");
        public final static Property CenaOplataSieciowa = new Property(3, String.class, "cenaOplataSieciowa", false, "CENA_OPLATA_SIECIOWA");
        public final static Property CenaOplataPrzejsciowa = new Property(4, String.class, "cenaOplataPrzejsciowa", false, "CENA_OPLATA_PRZEJSCIOWA");
        public final static Property CenaOplStalaZaPrzesyl = new Property(5, String.class, "cenaOplStalaZaPrzesyl", false, "CENA_OPL_STALA_ZA_PRZESYL");
        public final static Property CenaOplataAbonamentowa = new Property(6, String.class, "cenaOplataAbonamentowa", false, "CENA_OPLATA_ABONAMENTOWA");
    };


    public PgePricesDao(DaoConfig config) {
        super(config);
    }
    
    public PgePricesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PGE_PRICES' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'CENA_ZA_ENERGIE_CZYNNA' TEXT," + // 1: cenaZaEnergieCzynna
                "'CENA_SKLADNIK_JAKOSCIOWY' TEXT," + // 2: cenaSkladnikJakosciowy
                "'CENA_OPLATA_SIECIOWA' TEXT," + // 3: cenaOplataSieciowa
                "'CENA_OPLATA_PRZEJSCIOWA' TEXT," + // 4: cenaOplataPrzejsciowa
                "'CENA_OPL_STALA_ZA_PRZESYL' TEXT," + // 5: cenaOplStalaZaPrzesyl
                "'CENA_OPLATA_ABONAMENTOWA' TEXT);"); // 6: cenaOplataAbonamentowa
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PGE_PRICES'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PgePrices entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cenaZaEnergieCzynna = entity.getCenaZaEnergieCzynna();
        if (cenaZaEnergieCzynna != null) {
            stmt.bindString(2, cenaZaEnergieCzynna);
        }
 
        String cenaSkladnikJakosciowy = entity.getCenaSkladnikJakosciowy();
        if (cenaSkladnikJakosciowy != null) {
            stmt.bindString(3, cenaSkladnikJakosciowy);
        }
 
        String cenaOplataSieciowa = entity.getCenaOplataSieciowa();
        if (cenaOplataSieciowa != null) {
            stmt.bindString(4, cenaOplataSieciowa);
        }
 
        String cenaOplataPrzejsciowa = entity.getCenaOplataPrzejsciowa();
        if (cenaOplataPrzejsciowa != null) {
            stmt.bindString(5, cenaOplataPrzejsciowa);
        }
 
        String cenaOplStalaZaPrzesyl = entity.getCenaOplStalaZaPrzesyl();
        if (cenaOplStalaZaPrzesyl != null) {
            stmt.bindString(6, cenaOplStalaZaPrzesyl);
        }
 
        String cenaOplataAbonamentowa = entity.getCenaOplataAbonamentowa();
        if (cenaOplataAbonamentowa != null) {
            stmt.bindString(7, cenaOplataAbonamentowa);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PgePrices readEntity(Cursor cursor, int offset) {
        PgePrices entity = new PgePrices( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cenaZaEnergieCzynna
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cenaSkladnikJakosciowy
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // cenaOplataSieciowa
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // cenaOplataPrzejsciowa
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // cenaOplStalaZaPrzesyl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // cenaOplataAbonamentowa
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PgePrices entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCenaZaEnergieCzynna(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCenaSkladnikJakosciowy(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCenaOplataSieciowa(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCenaOplataPrzejsciowa(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCenaOplStalaZaPrzesyl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCenaOplataAbonamentowa(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PgePrices entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PgePrices entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
