package pl.srw.billcalculator.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "HISTORY".
 */
@Entity
public class History {

    @Id(autoincrement = true)
    private Long id;
    private java.util.Date dateFrom;
    private String billType;
    private Long billId;

    @Generated
    public History() {
    }

    public History(Long id) {
        this.id = id;
    }

    @Generated
    public History(Long id, java.util.Date dateFrom, String billType, Long billId) {
        this.id = id;
        this.dateFrom = dateFrom;
        this.billType = billType;
        this.billId = billId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(java.util.Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    public String getBillType() {
        return billType;
    }

    public void setBillType(String billType) {
        this.billType = billType;
    }

    public Long getBillId() {
        return billId;
    }

    public void setBillId(Long billId) {
        this.billId = billId;
    }

    @Override
    public String toString() {
        return "History{" +
                "id=" + id +
                ", dateFrom=" + dateFrom +
                ", billType='" + billType + '\'' +
                ", billId=" + billId +
                '}';
    }
}
