package pl.srw.billcalculator.db;

import org.greenrobot.greendao.DaoException;
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.ToOne;

import pl.srw.billcalculator.db.dao.DaoSession;
import pl.srw.billcalculator.db.dao.PgeG11BillDao;
import pl.srw.billcalculator.db.dao.PgePricesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "PGE_G11_BILL".
 */
@Entity(active = true)
public class PgeG11Bill implements Bill {

    @Id(autoincrement = true)
    private Long id;
    private Integer readingFrom;
    private Integer readingTo;
    private java.util.Date dateFrom;
    private java.util.Date dateTo;
    private Double amountToPay;
    private Long pricesId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient PgeG11BillDao myDao;

    @ToOne(joinProperty = "pricesId")
    private PgePrices pgePrices;

    @Generated
    private transient Long pgePrices__resolvedKey;

    @Generated
    public PgeG11Bill() {
    }

    public PgeG11Bill(Long id) {
        this.id = id;
    }

    @Generated
    public PgeG11Bill(Long id, Integer readingFrom, Integer readingTo, java.util.Date dateFrom, java.util.Date dateTo, Double amountToPay, Long pricesId) {
        this.id = id;
        this.readingFrom = readingFrom;
        this.readingTo = readingTo;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.amountToPay = amountToPay;
        this.pricesId = pricesId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getPgeG11BillDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getReadingFrom() {
        return readingFrom;
    }

    public void setReadingFrom(Integer readingFrom) {
        this.readingFrom = readingFrom;
    }

    public Integer getReadingTo() {
        return readingTo;
    }

    public void setReadingTo(Integer readingTo) {
        this.readingTo = readingTo;
    }

    public java.util.Date getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(java.util.Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    public java.util.Date getDateTo() {
        return dateTo;
    }

    public void setDateTo(java.util.Date dateTo) {
        this.dateTo = dateTo;
    }

    public Double getAmountToPay() {
        return amountToPay;
    }

    public void setAmountToPay(Double amountToPay) {
        this.amountToPay = amountToPay;
    }

    public Long getPricesId() {
        return pricesId;
    }

    public void setPricesId(Long pricesId) {
        this.pricesId = pricesId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public PgePrices getPgePrices() {
        Long __key = this.pricesId;
        if (pgePrices__resolvedKey == null || !pgePrices__resolvedKey.equals(__key)) {
            __throwIfDetached();
            PgePricesDao targetDao = daoSession.getPgePricesDao();
            PgePrices pgePricesNew = targetDao.load(__key);
            synchronized (this) {
                pgePrices = pgePricesNew;
            	pgePrices__resolvedKey = __key;
            }
        }
        return pgePrices;
    }

    @Generated
    public void setPgePrices(PgePrices pgePrices) {
        synchronized (this) {
            this.pgePrices = pgePrices;
            pricesId = pgePrices == null ? null : pgePrices.getId();
            pgePrices__resolvedKey = pricesId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    @Override
    public String toString() {
        return "PgeG11Bill{" +
                "id=" + id +
                ", readingFrom=" + readingFrom +
                ", readingTo=" + readingTo +
                ", dateFrom=" + dateFrom +
                ", dateTo=" + dateTo +
                ", amountToPay=" + amountToPay +
                ", pricesId=" + pricesId +
                ", daoSession=" + daoSession +
                ", myDao=" + myDao +
                ", pgePrices=" + pgePrices +
                ", pgePrices__resolvedKey=" + pgePrices__resolvedKey +
                '}';
    }

}
