package pl.srw.billcalculator.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PGE_G12_PRICES.
 */
public class PgeG12Prices {

    private Long id;
    private String cenaZaEnergieCzynnaDzien;
    private String cenaZaEnergieCzynnaNoc;
    private String cenaSkladnikJakosciowy;
    private String cenaOplataSieciowaDzien;
    private String cenaOplataSieciowaNoc;
    private String cenaOplataPrzejsciowa;
    private String cenaOplStalaZaPrzesyl;
    private String cenaOplataAbonamentowa;

    public PgeG12Prices() {
    }

    public PgeG12Prices(Long id) {
        this.id = id;
    }

    public PgeG12Prices(Long id, String cenaZaEnergieCzynnaDzien, String cenaZaEnergieCzynnaNoc, String cenaSkladnikJakosciowy, String cenaOplataSieciowaDzien, String cenaOplataSieciowaNoc, String cenaOplataPrzejsciowa, String cenaOplStalaZaPrzesyl, String cenaOplataAbonamentowa) {
        this.id = id;
        this.cenaZaEnergieCzynnaDzien = cenaZaEnergieCzynnaDzien;
        this.cenaZaEnergieCzynnaNoc = cenaZaEnergieCzynnaNoc;
        this.cenaSkladnikJakosciowy = cenaSkladnikJakosciowy;
        this.cenaOplataSieciowaDzien = cenaOplataSieciowaDzien;
        this.cenaOplataSieciowaNoc = cenaOplataSieciowaNoc;
        this.cenaOplataPrzejsciowa = cenaOplataPrzejsciowa;
        this.cenaOplStalaZaPrzesyl = cenaOplStalaZaPrzesyl;
        this.cenaOplataAbonamentowa = cenaOplataAbonamentowa;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCenaZaEnergieCzynnaDzien() {
        return cenaZaEnergieCzynnaDzien;
    }

    public void setCenaZaEnergieCzynnaDzien(String cenaZaEnergieCzynnaDzien) {
        this.cenaZaEnergieCzynnaDzien = cenaZaEnergieCzynnaDzien;
    }

    public String getCenaZaEnergieCzynnaNoc() {
        return cenaZaEnergieCzynnaNoc;
    }

    public void setCenaZaEnergieCzynnaNoc(String cenaZaEnergieCzynnaNoc) {
        this.cenaZaEnergieCzynnaNoc = cenaZaEnergieCzynnaNoc;
    }

    public String getCenaSkladnikJakosciowy() {
        return cenaSkladnikJakosciowy;
    }

    public void setCenaSkladnikJakosciowy(String cenaSkladnikJakosciowy) {
        this.cenaSkladnikJakosciowy = cenaSkladnikJakosciowy;
    }

    public String getCenaOplataSieciowaDzien() {
        return cenaOplataSieciowaDzien;
    }

    public void setCenaOplataSieciowaDzien(String cenaOplataSieciowaDzien) {
        this.cenaOplataSieciowaDzien = cenaOplataSieciowaDzien;
    }

    public String getCenaOplataSieciowaNoc() {
        return cenaOplataSieciowaNoc;
    }

    public void setCenaOplataSieciowaNoc(String cenaOplataSieciowaNoc) {
        this.cenaOplataSieciowaNoc = cenaOplataSieciowaNoc;
    }

    public String getCenaOplataPrzejsciowa() {
        return cenaOplataPrzejsciowa;
    }

    public void setCenaOplataPrzejsciowa(String cenaOplataPrzejsciowa) {
        this.cenaOplataPrzejsciowa = cenaOplataPrzejsciowa;
    }

    public String getCenaOplStalaZaPrzesyl() {
        return cenaOplStalaZaPrzesyl;
    }

    public void setCenaOplStalaZaPrzesyl(String cenaOplStalaZaPrzesyl) {
        this.cenaOplStalaZaPrzesyl = cenaOplStalaZaPrzesyl;
    }

    public String getCenaOplataAbonamentowa() {
        return cenaOplataAbonamentowa;
    }

    public void setCenaOplataAbonamentowa(String cenaOplataAbonamentowa) {
        this.cenaOplataAbonamentowa = cenaOplataAbonamentowa;
    }

}
