package pl.srw.billcalculator.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PGE_PRICES.
 */
public class PgePrices {

    private Long id;
    private String cenaZaEnergieCzynna;
    private String cenaSkladnikJakosciowy;
    private String cenaOplataSieciowa;
    private String cenaOplataPrzejsciowa;
    private String cenaOplStalaZaPrzesyl;
    private String cenaOplataAbonamentowa;

    public PgePrices() {
    }

    public PgePrices(Long id) {
        this.id = id;
    }

    public PgePrices(Long id, String cenaZaEnergieCzynna, String cenaSkladnikJakosciowy, String cenaOplataSieciowa, String cenaOplataPrzejsciowa, String cenaOplStalaZaPrzesyl, String cenaOplataAbonamentowa) {
        this.id = id;
        this.cenaZaEnergieCzynna = cenaZaEnergieCzynna;
        this.cenaSkladnikJakosciowy = cenaSkladnikJakosciowy;
        this.cenaOplataSieciowa = cenaOplataSieciowa;
        this.cenaOplataPrzejsciowa = cenaOplataPrzejsciowa;
        this.cenaOplStalaZaPrzesyl = cenaOplStalaZaPrzesyl;
        this.cenaOplataAbonamentowa = cenaOplataAbonamentowa;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCenaZaEnergieCzynna() {
        return cenaZaEnergieCzynna;
    }

    public void setCenaZaEnergieCzynna(String cenaZaEnergieCzynna) {
        this.cenaZaEnergieCzynna = cenaZaEnergieCzynna;
    }

    public String getCenaSkladnikJakosciowy() {
        return cenaSkladnikJakosciowy;
    }

    public void setCenaSkladnikJakosciowy(String cenaSkladnikJakosciowy) {
        this.cenaSkladnikJakosciowy = cenaSkladnikJakosciowy;
    }

    public String getCenaOplataSieciowa() {
        return cenaOplataSieciowa;
    }

    public void setCenaOplataSieciowa(String cenaOplataSieciowa) {
        this.cenaOplataSieciowa = cenaOplataSieciowa;
    }

    public String getCenaOplataPrzejsciowa() {
        return cenaOplataPrzejsciowa;
    }

    public void setCenaOplataPrzejsciowa(String cenaOplataPrzejsciowa) {
        this.cenaOplataPrzejsciowa = cenaOplataPrzejsciowa;
    }

    public String getCenaOplStalaZaPrzesyl() {
        return cenaOplStalaZaPrzesyl;
    }

    public void setCenaOplStalaZaPrzesyl(String cenaOplStalaZaPrzesyl) {
        this.cenaOplStalaZaPrzesyl = cenaOplStalaZaPrzesyl;
    }

    public String getCenaOplataAbonamentowa() {
        return cenaOplataAbonamentowa;
    }

    public void setCenaOplataAbonamentowa(String cenaOplataAbonamentowa) {
        this.cenaOplataAbonamentowa = cenaOplataAbonamentowa;
    }

}
