package pl.srw.billcalculator.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PGE_PRICES.
 */
public class PgePrices implements pl.srw.billcalculator.pojo.IPgePrices, java.io.Serializable {

    private Long id;
    private String zaEnergieCzynna;
    private String skladnikJakosciowy;
    private String oplataSieciowa;
    private String oplataPrzejsciowa;
    private String oplataStalaZaPrzesyl;
    private String oplataAbonamentowa;
    private String zaEnergieCzynnaDzien;
    private String zaEnergieCzynnaNoc;
    private String oplataSieciowaDzien;
    private String oplataSieciowaNoc;

    public PgePrices() {
    }

    public PgePrices(Long id) {
        this.id = id;
    }

    public PgePrices(Long id, String zaEnergieCzynna, String skladnikJakosciowy, String oplataSieciowa, String oplataPrzejsciowa, String oplataStalaZaPrzesyl, String oplataAbonamentowa, String zaEnergieCzynnaDzien, String zaEnergieCzynnaNoc, String oplataSieciowaDzien, String oplataSieciowaNoc) {
        this.id = id;
        this.zaEnergieCzynna = zaEnergieCzynna;
        this.skladnikJakosciowy = skladnikJakosciowy;
        this.oplataSieciowa = oplataSieciowa;
        this.oplataPrzejsciowa = oplataPrzejsciowa;
        this.oplataStalaZaPrzesyl = oplataStalaZaPrzesyl;
        this.oplataAbonamentowa = oplataAbonamentowa;
        this.zaEnergieCzynnaDzien = zaEnergieCzynnaDzien;
        this.zaEnergieCzynnaNoc = zaEnergieCzynnaNoc;
        this.oplataSieciowaDzien = oplataSieciowaDzien;
        this.oplataSieciowaNoc = oplataSieciowaNoc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getZaEnergieCzynna() {
        return zaEnergieCzynna;
    }

    public void setZaEnergieCzynna(String zaEnergieCzynna) {
        this.zaEnergieCzynna = zaEnergieCzynna;
    }

    public String getSkladnikJakosciowy() {
        return skladnikJakosciowy;
    }

    public void setSkladnikJakosciowy(String skladnikJakosciowy) {
        this.skladnikJakosciowy = skladnikJakosciowy;
    }

    public String getOplataSieciowa() {
        return oplataSieciowa;
    }

    public void setOplataSieciowa(String oplataSieciowa) {
        this.oplataSieciowa = oplataSieciowa;
    }

    public String getOplataPrzejsciowa() {
        return oplataPrzejsciowa;
    }

    public void setOplataPrzejsciowa(String oplataPrzejsciowa) {
        this.oplataPrzejsciowa = oplataPrzejsciowa;
    }

    public String getOplataStalaZaPrzesyl() {
        return oplataStalaZaPrzesyl;
    }

    public void setOplataStalaZaPrzesyl(String oplataStalaZaPrzesyl) {
        this.oplataStalaZaPrzesyl = oplataStalaZaPrzesyl;
    }

    public String getOplataAbonamentowa() {
        return oplataAbonamentowa;
    }

    public void setOplataAbonamentowa(String oplataAbonamentowa) {
        this.oplataAbonamentowa = oplataAbonamentowa;
    }

    public String getZaEnergieCzynnaDzien() {
        return zaEnergieCzynnaDzien;
    }

    public void setZaEnergieCzynnaDzien(String zaEnergieCzynnaDzien) {
        this.zaEnergieCzynnaDzien = zaEnergieCzynnaDzien;
    }

    public String getZaEnergieCzynnaNoc() {
        return zaEnergieCzynnaNoc;
    }

    public void setZaEnergieCzynnaNoc(String zaEnergieCzynnaNoc) {
        this.zaEnergieCzynnaNoc = zaEnergieCzynnaNoc;
    }

    public String getOplataSieciowaDzien() {
        return oplataSieciowaDzien;
    }

    public void setOplataSieciowaDzien(String oplataSieciowaDzien) {
        this.oplataSieciowaDzien = oplataSieciowaDzien;
    }

    public String getOplataSieciowaNoc() {
        return oplataSieciowaNoc;
    }

    public void setOplataSieciowaNoc(String oplataSieciowaNoc) {
        this.oplataSieciowaNoc = oplataSieciowaNoc;
    }

}
