package pl.srw.billcalculator.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PGNIG_PRICES.
 */
public class PgnigPrices {

    private Long id;
    private String oplataAbonamentowa;
    private String paliwoGazowe;
    private String dystrybucyjnaStala;
    private String dystrybucyjnaZmienna;
    private String wspKonwersji;

    public PgnigPrices() {
    }

    public PgnigPrices(Long id) {
        this.id = id;
    }

    public PgnigPrices(Long id, String oplataAbonamentowa, String paliwoGazowe, String dystrybucyjnaStala, String dystrybucyjnaZmienna, String wspKonwersji) {
        this.id = id;
        this.oplataAbonamentowa = oplataAbonamentowa;
        this.paliwoGazowe = paliwoGazowe;
        this.dystrybucyjnaStala = dystrybucyjnaStala;
        this.dystrybucyjnaZmienna = dystrybucyjnaZmienna;
        this.wspKonwersji = wspKonwersji;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOplataAbonamentowa() {
        return oplataAbonamentowa;
    }

    public void setOplataAbonamentowa(String oplataAbonamentowa) {
        this.oplataAbonamentowa = oplataAbonamentowa;
    }

    public String getPaliwoGazowe() {
        return paliwoGazowe;
    }

    public void setPaliwoGazowe(String paliwoGazowe) {
        this.paliwoGazowe = paliwoGazowe;
    }

    public String getDystrybucyjnaStala() {
        return dystrybucyjnaStala;
    }

    public void setDystrybucyjnaStala(String dystrybucyjnaStala) {
        this.dystrybucyjnaStala = dystrybucyjnaStala;
    }

    public String getDystrybucyjnaZmienna() {
        return dystrybucyjnaZmienna;
    }

    public void setDystrybucyjnaZmienna(String dystrybucyjnaZmienna) {
        this.dystrybucyjnaZmienna = dystrybucyjnaZmienna;
    }

    public String getWspKonwersji() {
        return wspKonwersji;
    }

    public void setWspKonwersji(String wspKonwersji) {
        this.wspKonwersji = wspKonwersji;
    }

}
