package pl.srw.billcalculator.db;

import org.greenrobot.greendao.annotation.*;

import pl.srw.billcalculator.db.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

import pl.srw.billcalculator.db.dao.PgnigBillDao;
import pl.srw.billcalculator.db.dao.PgnigPricesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "PGNIG_BILL".
 */
@Entity(active = true)
public class PgnigBill implements Bill {

    @Id
    private Long id;
    private Integer readingFrom;
    private Integer readingTo;
    private java.util.Date dateFrom;
    private java.util.Date dateTo;
    private Double amountToPay;
    private Long pricesId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient PgnigBillDao myDao;

    @ToOne(joinProperty = "pricesId")
    private PgnigPrices pgnigPrices;

    @Generated
    private transient Long pgnigPrices__resolvedKey;

    @Generated
    public PgnigBill() {
    }

    public PgnigBill(Long id) {
        this.id = id;
    }

    @Generated
    public PgnigBill(Long id, Integer readingFrom, Integer readingTo, java.util.Date dateFrom, java.util.Date dateTo, Double amountToPay, Long pricesId) {
        this.id = id;
        this.readingFrom = readingFrom;
        this.readingTo = readingTo;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.amountToPay = amountToPay;
        this.pricesId = pricesId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getPgnigBillDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getReadingFrom() {
        return readingFrom;
    }

    public void setReadingFrom(Integer readingFrom) {
        this.readingFrom = readingFrom;
    }

    public Integer getReadingTo() {
        return readingTo;
    }

    public void setReadingTo(Integer readingTo) {
        this.readingTo = readingTo;
    }

    public java.util.Date getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(java.util.Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    public java.util.Date getDateTo() {
        return dateTo;
    }

    public void setDateTo(java.util.Date dateTo) {
        this.dateTo = dateTo;
    }

    public Double getAmountToPay() {
        return amountToPay;
    }

    public void setAmountToPay(Double amountToPay) {
        this.amountToPay = amountToPay;
    }

    public Long getPricesId() {
        return pricesId;
    }

    public void setPricesId(Long pricesId) {
        this.pricesId = pricesId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public PgnigPrices getPgnigPrices() {
        Long __key = this.pricesId;
        if (pgnigPrices__resolvedKey == null || !pgnigPrices__resolvedKey.equals(__key)) {
            __throwIfDetached();
            PgnigPricesDao targetDao = daoSession.getPgnigPricesDao();
            PgnigPrices pgnigPricesNew = targetDao.load(__key);
            synchronized (this) {
                pgnigPrices = pgnigPricesNew;
            	pgnigPrices__resolvedKey = __key;
            }
        }
        return pgnigPrices;
    }

    @Generated
    public void setPgnigPrices(PgnigPrices pgnigPrices) {
        synchronized (this) {
            this.pgnigPrices = pgnigPrices;
            pricesId = pgnigPrices == null ? null : pgnigPrices.getId();
            pgnigPrices__resolvedKey = pricesId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    @Override
    public String toString() {
        return "PgnigBill{" +
                "id=" + id +
                ", readingFrom=" + readingFrom +
                ", readingTo=" + readingTo +
                ", dateFrom=" + dateFrom +
                ", dateTo=" + dateTo +
                ", amountToPay=" + amountToPay +
                ", pricesId=" + pricesId +
                ", daoSession=" + daoSession +
                ", myDao=" + myDao +
                ", pgnigPrices=" + pgnigPrices +
                ", pgnigPrices__resolvedKey=" + pgnigPrices__resolvedKey +
                '}';
    }
}
