package pl.srw.billcalculator.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "PGNIG_PRICES".
 */
@Entity
public class PgnigPrices implements pl.srw.billcalculator.pojo.IPgnigPrices, java.io.Serializable {

    @Id(autoincrement = true)
    private Long id;
    private String oplataAbonamentowa;
    private String paliwoGazowe;
    private String dystrybucyjnaStala;
    private String dystrybucyjnaZmienna;
    private String wspolczynnikKonwersji;

    @Generated
    public PgnigPrices() {
    }

    public PgnigPrices(Long id) {
        this.id = id;
    }

    @Generated
    public PgnigPrices(Long id, String oplataAbonamentowa, String paliwoGazowe, String dystrybucyjnaStala, String dystrybucyjnaZmienna, String wspolczynnikKonwersji) {
        this.id = id;
        this.oplataAbonamentowa = oplataAbonamentowa;
        this.paliwoGazowe = paliwoGazowe;
        this.dystrybucyjnaStala = dystrybucyjnaStala;
        this.dystrybucyjnaZmienna = dystrybucyjnaZmienna;
        this.wspolczynnikKonwersji = wspolczynnikKonwersji;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOplataAbonamentowa() {
        return oplataAbonamentowa;
    }

    public void setOplataAbonamentowa(String oplataAbonamentowa) {
        this.oplataAbonamentowa = oplataAbonamentowa;
    }

    public String getPaliwoGazowe() {
        return paliwoGazowe;
    }

    public void setPaliwoGazowe(String paliwoGazowe) {
        this.paliwoGazowe = paliwoGazowe;
    }

    public String getDystrybucyjnaStala() {
        return dystrybucyjnaStala;
    }

    public void setDystrybucyjnaStala(String dystrybucyjnaStala) {
        this.dystrybucyjnaStala = dystrybucyjnaStala;
    }

    public String getDystrybucyjnaZmienna() {
        return dystrybucyjnaZmienna;
    }

    public void setDystrybucyjnaZmienna(String dystrybucyjnaZmienna) {
        this.dystrybucyjnaZmienna = dystrybucyjnaZmienna;
    }

    public String getWspolczynnikKonwersji() {
        return wspolczynnikKonwersji;
    }

    public void setWspolczynnikKonwersji(String wspolczynnikKonwersji) {
        this.wspolczynnikKonwersji = wspolczynnikKonwersji;
    }

}
