package pl.srw.billcalculator.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "TAURON_PRICES".
 */
@Entity
public class TauronPrices implements pl.srw.billcalculator.pojo.ITauronPrices, java.io.Serializable {

    @Id(autoincrement = true)
    private Long id;
    private String energiaElektrycznaCzynna;
    private String oplataDystrybucyjnaZmienna;
    private String oplataDystrybucyjnaStala;
    private String oplataPrzejsciowa;
    private String oplataAbonamentowa;
    private String energiaElektrycznaCzynnaDzien;
    private String energiaElektrycznaCzynnaNoc;
    private String oplataDystrybucyjnaZmiennaDzien;
    private String oplataDystrybucyjnaZmiennaNoc;
    private String oplataOze;

    @Generated
    public TauronPrices() {
    }

    public TauronPrices(Long id) {
        this.id = id;
    }

    @Generated
    public TauronPrices(Long id, String energiaElektrycznaCzynna, String oplataDystrybucyjnaZmienna, String oplataDystrybucyjnaStala, String oplataPrzejsciowa, String oplataAbonamentowa, String energiaElektrycznaCzynnaDzien, String energiaElektrycznaCzynnaNoc, String oplataDystrybucyjnaZmiennaDzien, String oplataDystrybucyjnaZmiennaNoc, String oplataOze) {
        this.id = id;
        this.energiaElektrycznaCzynna = energiaElektrycznaCzynna;
        this.oplataDystrybucyjnaZmienna = oplataDystrybucyjnaZmienna;
        this.oplataDystrybucyjnaStala = oplataDystrybucyjnaStala;
        this.oplataPrzejsciowa = oplataPrzejsciowa;
        this.oplataAbonamentowa = oplataAbonamentowa;
        this.energiaElektrycznaCzynnaDzien = energiaElektrycznaCzynnaDzien;
        this.energiaElektrycznaCzynnaNoc = energiaElektrycznaCzynnaNoc;
        this.oplataDystrybucyjnaZmiennaDzien = oplataDystrybucyjnaZmiennaDzien;
        this.oplataDystrybucyjnaZmiennaNoc = oplataDystrybucyjnaZmiennaNoc;
        this.oplataOze = oplataOze;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEnergiaElektrycznaCzynna() {
        return energiaElektrycznaCzynna;
    }

    public void setEnergiaElektrycznaCzynna(String energiaElektrycznaCzynna) {
        this.energiaElektrycznaCzynna = energiaElektrycznaCzynna;
    }

    public String getOplataDystrybucyjnaZmienna() {
        return oplataDystrybucyjnaZmienna;
    }

    public void setOplataDystrybucyjnaZmienna(String oplataDystrybucyjnaZmienna) {
        this.oplataDystrybucyjnaZmienna = oplataDystrybucyjnaZmienna;
    }

    public String getOplataDystrybucyjnaStala() {
        return oplataDystrybucyjnaStala;
    }

    public void setOplataDystrybucyjnaStala(String oplataDystrybucyjnaStala) {
        this.oplataDystrybucyjnaStala = oplataDystrybucyjnaStala;
    }

    public String getOplataPrzejsciowa() {
        return oplataPrzejsciowa;
    }

    public void setOplataPrzejsciowa(String oplataPrzejsciowa) {
        this.oplataPrzejsciowa = oplataPrzejsciowa;
    }

    public String getOplataAbonamentowa() {
        return oplataAbonamentowa;
    }

    public void setOplataAbonamentowa(String oplataAbonamentowa) {
        this.oplataAbonamentowa = oplataAbonamentowa;
    }

    public String getEnergiaElektrycznaCzynnaDzien() {
        return energiaElektrycznaCzynnaDzien;
    }

    public void setEnergiaElektrycznaCzynnaDzien(String energiaElektrycznaCzynnaDzien) {
        this.energiaElektrycznaCzynnaDzien = energiaElektrycznaCzynnaDzien;
    }

    public String getEnergiaElektrycznaCzynnaNoc() {
        return energiaElektrycznaCzynnaNoc;
    }

    public void setEnergiaElektrycznaCzynnaNoc(String energiaElektrycznaCzynnaNoc) {
        this.energiaElektrycznaCzynnaNoc = energiaElektrycznaCzynnaNoc;
    }

    public String getOplataDystrybucyjnaZmiennaDzien() {
        return oplataDystrybucyjnaZmiennaDzien;
    }

    public void setOplataDystrybucyjnaZmiennaDzien(String oplataDystrybucyjnaZmiennaDzien) {
        this.oplataDystrybucyjnaZmiennaDzien = oplataDystrybucyjnaZmiennaDzien;
    }

    public String getOplataDystrybucyjnaZmiennaNoc() {
        return oplataDystrybucyjnaZmiennaNoc;
    }

    public void setOplataDystrybucyjnaZmiennaNoc(String oplataDystrybucyjnaZmiennaNoc) {
        this.oplataDystrybucyjnaZmiennaNoc = oplataDystrybucyjnaZmiennaNoc;
    }

    public String getOplataOze() {
        return oplataOze;
    }

    public void setOplataOze(String oplataOze) {
        this.oplataOze = oplataOze;
    }

}
