package pl.srw.billcalculator.db;

import org.greenrobot.greendao.DaoException;
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.ToOne;

import pl.srw.billcalculator.db.dao.DaoSession;
import pl.srw.billcalculator.db.dao.TauronG12BillDao;
import pl.srw.billcalculator.db.dao.TauronPricesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "TAURON_G12_BILL".
 */
@Entity(active = true)
public class TauronG12Bill implements Bill {

    @Id(autoincrement = true)
    private Long id;
    private Integer readingDayFrom;
    private Integer readingDayTo;
    private Integer readingNightFrom;
    private Integer readingNightTo;
    private java.util.Date dateFrom;
    private java.util.Date dateTo;
    private Double amountToPay;
    private Long pricesId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient TauronG12BillDao myDao;

    @ToOne(joinProperty = "pricesId")
    private TauronPrices tauronPrices;

    @Generated
    private transient Long tauronPrices__resolvedKey;

    @Generated
    public TauronG12Bill() {
    }

    public TauronG12Bill(Long id) {
        this.id = id;
    }

    @Generated
    public TauronG12Bill(Long id, Integer readingDayFrom, Integer readingDayTo, Integer readingNightFrom, Integer readingNightTo, java.util.Date dateFrom, java.util.Date dateTo, Double amountToPay, Long pricesId) {
        this.id = id;
        this.readingDayFrom = readingDayFrom;
        this.readingDayTo = readingDayTo;
        this.readingNightFrom = readingNightFrom;
        this.readingNightTo = readingNightTo;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.amountToPay = amountToPay;
        this.pricesId = pricesId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTauronG12BillDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getReadingDayFrom() {
        return readingDayFrom;
    }

    public void setReadingDayFrom(Integer readingDayFrom) {
        this.readingDayFrom = readingDayFrom;
    }

    public Integer getReadingDayTo() {
        return readingDayTo;
    }

    public void setReadingDayTo(Integer readingDayTo) {
        this.readingDayTo = readingDayTo;
    }

    public Integer getReadingNightFrom() {
        return readingNightFrom;
    }

    public void setReadingNightFrom(Integer readingNightFrom) {
        this.readingNightFrom = readingNightFrom;
    }

    public Integer getReadingNightTo() {
        return readingNightTo;
    }

    public void setReadingNightTo(Integer readingNightTo) {
        this.readingNightTo = readingNightTo;
    }

    public java.util.Date getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(java.util.Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    public java.util.Date getDateTo() {
        return dateTo;
    }

    public void setDateTo(java.util.Date dateTo) {
        this.dateTo = dateTo;
    }

    public Double getAmountToPay() {
        return amountToPay;
    }

    public void setAmountToPay(Double amountToPay) {
        this.amountToPay = amountToPay;
    }

    public Long getPricesId() {
        return pricesId;
    }

    public void setPricesId(Long pricesId) {
        this.pricesId = pricesId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public TauronPrices getTauronPrices() {
        Long __key = this.pricesId;
        if (tauronPrices__resolvedKey == null || !tauronPrices__resolvedKey.equals(__key)) {
            __throwIfDetached();
            TauronPricesDao targetDao = daoSession.getTauronPricesDao();
            TauronPrices tauronPricesNew = targetDao.load(__key);
            synchronized (this) {
                tauronPrices = tauronPricesNew;
            	tauronPrices__resolvedKey = __key;
            }
        }
        return tauronPrices;
    }

    @Generated
    public void setTauronPrices(TauronPrices tauronPrices) {
        synchronized (this) {
            this.tauronPrices = tauronPrices;
            pricesId = tauronPrices == null ? null : tauronPrices.getId();
            tauronPrices__resolvedKey = pricesId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    @Override
    public String toString() {
        return "TauronG12Bill{" +
                "id=" + id +
                ", readingDayFrom=" + readingDayFrom +
                ", readingDayTo=" + readingDayTo +
                ", readingNightFrom=" + readingNightFrom +
                ", readingNightTo=" + readingNightTo +
                ", dateFrom=" + dateFrom +
                ", dateTo=" + dateTo +
                ", amountToPay=" + amountToPay +
                ", pricesId=" + pricesId +
                ", daoSession=" + daoSession +
                ", myDao=" + myDao +
                ", tauronPrices=" + tauronPrices +
                ", tauronPrices__resolvedKey=" + tauronPrices__resolvedKey +
                '}';
    }
}
